[package]
name = "zkverifier"
version = "0.1.0"
description = "ZK Verifier on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
groth16-solana = { git = "https://github.com/Lightprotocol/groth16-solana.git", branch = "main" }  # For Groth16 verification
solana-program = "1.18.0"
