[features]
seeds = false
skip-lint = false

[programs.localnet]
zkverifier = "YourProgramIdHere"  # Replace after deploy

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"